/** Contract shared by every printable page (same role as tintbrew's ScenarioDef). */
export interface PageDef {
  /** Flat URL slug, e.g. 'place-value-chart' -> /place-value-chart/ */
  slug: string;
  /** Full route path when it is not `/${slug}` — cursive letters live at /cursive/<slug>/. */
  path?: string;
  /** Which hub owns the page (drives breadcrumb + footer grouping). */
  hub: 'charts' | 'sight-words' | 'cursive' | 'graph-paper' | 'halloween';
  h1: string;
  metaTitle: string;
  metaDescription: string;
  lead: string;
  introHeading: string;
  /** Hand-written teaching facts — the anti-thin-content layer. */
  intro: string[];
  /** Optional second prose block (cursive letters: the "capital X in cursive" deep-dive). */
  extraSection?: { heading: string; paras: string[] };
  /** Small print hint above the sheet, e.g. 'Fits one letter page, portrait.' */
  printNote: string;
  tips: { title: string; body: string }[];
  faqs: { q: string; a: string }[];
  related: { href: string; label: string }[];
  /** Interactive printable -> also gets WebApplication JSON-LD. */
  interactive?: boolean;
  /**
   * In-content preview image of the printable itself — the Google Images
   * channel (page HTML is a table/SVG otherwise, which image search can't
   * index). Generated by `npm run sheet-images`; src/width/height must match
   * the PNG on disk (guarded by sheetImages.test.ts).
   */
  sheetImage?: {
    src: string;
    alt: string;
    width: number;
    height: number;
    caption?: string;
  };
  /** Wide sheets (1-20 grids, number lines) print landscape. */
  landscape?: boolean;
}
