import { describe, expect, it } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PNG } from 'pngjs';
import { multiplicationPages } from './multiplication';
import { placeValuePages } from './placeValue';
import { sightWordPages } from './sightWordsContent';
import { cursivePages } from './cursive';
import { loosePages } from './loose';
import type { PageDef } from './pageTypes';

/**
 * The Google Images channel (PLAN #17): pages declare a sheetImage whose
 * src/width/height must match a real PNG in public/images/ (generated by
 * `npm run sheet-images`). A mismatch = broken image or layout shift.
 */
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const PILLARS = [
  'multiplication-chart',
  'place-value-chart',
  'kindergarten-sight-words',
  'cursive-alphabet',
  'alphabet-chart',
];

const all: PageDef[] = [
  ...multiplicationPages,
  ...placeValuePages,
  ...sightWordPages,
  ...cursivePages,
  ...loosePages,
];
const withImages = all.filter((d) => d.sheetImage);

describe('sheetImage (Google Images channel)', () => {
  it('exactly the five pillar pages carry a sheet image', () => {
    expect(withImages.map((d) => d.slug).sort()).toEqual([...PILLARS].sort());
  });

  for (const def of withImages) {
    it(`${def.slug}: src resolves and declared dimensions match the PNG on disk`, () => {
      const img = def.sheetImage!;
      expect(img.src.startsWith('/images/')).toBe(true);
      expect(img.alt.endsWith('.')).toBe(true);
      expect(img.alt.length).toBeGreaterThan(60);
      const file = resolve(ROOT, 'public', img.src.slice(1));
      expect(existsSync(file), `${img.src} missing — run npm run sheet-images`).toBe(true);
      const png = PNG.sync.read(readFileSync(file));
      expect(png.width, 'width must match the generated PNG (rerun npm run sheet-images)').toBe(img.width);
      expect(png.height, 'height must match the generated PNG (rerun npm run sheet-images)').toBe(img.height);
    });
  }
});

/**
 * The Download PNG button (PLAN #18): the toolbar anchor is driven purely by
 * sheetImage, so these dist guards only run after a build (their order in the
 * release flow is build → vitest). They pin the mobile path — no Ctrl+P on a
 * phone, download-then-print is the real journey.
 */
const DIST = resolve(ROOT, 'dist');
const pillarDistReady = withImages.every((d) => existsSync(resolve(DIST, d.slug, 'index.html')));

describe.skipIf(!pillarDistReady)('Download PNG button (PLAN #18)', () => {
  for (const def of withImages) {
    it(`${def.slug}: built page exposes its sheet PNG as a download`, () => {
      const html = readFileSync(resolve(DIST, def.slug, 'index.html'), 'utf8');
      expect(
        new RegExp(`href="${def.sheetImage!.src.replace(/\//g, '\\/')}"[^>]*\\bdownload\\b`).test(html),
        'toolbar must carry <a href="…" download> for the sheet PNG',
      ).toBe(true);
    });
  }

  it('a page without a sheet image carries no download anchor', () => {
    const html = readFileSync(resolve(DIST, 'cursive', 'a', 'index.html'), 'utf8');
    expect(html).not.toContain('<a class="btn" href="/images/');
  });
});
